[package]
name = "pc"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.32.0"
iced = "0.13.1"
interfaces.workspace = true
logic.workspace = true
serial2-tokio = "0.1.15"
tokio = {version = "1.47.0", features = ["full"]}
